# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HcqiTool
                                 A QGIS plugin
 An open source GIS application for spatial analysis of health care quality indicators
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-11-06
        copyright            : (C) 2019 by Duarte et al
        email                : liaduarte@fc.up.pt
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load HcqiTool class from file HcqiTool.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .hcqi_tool import HcqiTool
    return HcqiTool(iface)
