# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hcqi_tool_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HcqiToolDialogBase(object):
    def setupUi(self, HcqiToolDialogBase):
        HcqiToolDialogBase.setObjectName("HcqiToolDialogBase")
        HcqiToolDialogBase.resize(400, 393)
        self.tabWidget = QtWidgets.QTabWidget(HcqiToolDialogBase)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 381, 371))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(220, 310, 111, 31))
        self.pushButton.setObjectName("pushButton")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 220, 351, 81))
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 91, 16))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 61, 16))
        self.label_2.setObjectName("label_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setGeometry(QtCore.QRect(180, 20, 141, 21))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_3.setGeometry(QtCore.QRect(180, 50, 141, 21))
        self.comboBox_3.setObjectName("comboBox_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 351, 80))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(20, 20, 81, 21))
        self.label_7.setObjectName("label_7")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(20, 50, 81, 21))
        self.label.setObjectName("label")
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_5.setGeometry(QtCore.QRect(180, 20, 141, 21))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setGeometry(QtCore.QRect(180, 50, 141, 21))
        self.comboBox.setObjectName("comboBox")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 90, 351, 111))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(20, 20, 81, 21))
        self.label_9.setObjectName("label_9")
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_6.setGeometry(QtCore.QRect(180, 20, 141, 21))
        self.comboBox_6.setObjectName("comboBox_6")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(20, 50, 81, 21))
        self.label_10.setObjectName("label_10")
        self.comboBox_7 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_7.setGeometry(QtCore.QRect(180, 50, 141, 21))
        self.comboBox_7.setObjectName("comboBox_7")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(20, 80, 81, 21))
        self.label_11.setObjectName("label_11")
        self.comboBox_8 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_8.setGeometry(QtCore.QRect(180, 80, 141, 21))
        self.comboBox_8.setObjectName("comboBox_8")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.checkBox = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox.setGeometry(QtCore.QRect(30, 20, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(260, 260, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 120, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 220, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 260, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit.setGeometry(QtCore.QRect(20, 180, 211, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(20, 160, 121, 16))
        self.label_8.setObjectName("label_8")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_7.setGeometry(QtCore.QRect(240, 180, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_2.setGeometry(QtCore.QRect(30, 50, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_3.setGeometry(QtCore.QRect(30, 80, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 300, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(HcqiToolDialogBase)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(HcqiToolDialogBase)

    def retranslateUi(self, HcqiToolDialogBase):
        _translate = QtCore.QCoreApplication.translate
        HcqiToolDialogBase.setWindowTitle(_translate("HcqiToolDialogBase", "HCQI Tool"))
        self.pushButton.setText(_translate("HcqiToolDialogBase", "Classify"))
        self.groupBox.setTitle(_translate("HcqiToolDialogBase", "Style"))
        self.label_3.setText(_translate("HcqiToolDialogBase", "Color Ramp"))
        self.label_2.setText(_translate("HcqiToolDialogBase", "Style"))
        self.groupBox_2.setTitle(_translate("HcqiToolDialogBase", "GroupBox"))
        self.label_7.setText(_translate("HcqiToolDialogBase", "Level"))
        self.label.setText(_translate("HcqiToolDialogBase", "Attribute"))
        self.groupBox_3.setTitle(_translate("HcqiToolDialogBase", "Filters"))
        self.label_9.setText(_translate("HcqiToolDialogBase", "PQI"))
        self.label_10.setText(_translate("HcqiToolDialogBase", "Year"))
        self.label_11.setText(_translate("HcqiToolDialogBase", "Codification"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("HcqiToolDialogBase", "Symbology"))
        self.checkBox.setText(_translate("HcqiToolDialogBase", "Open Web Map"))
        self.pushButton_3.setText(_translate("HcqiToolDialogBase", "HELP"))
        self.pushButton_4.setText(_translate("HcqiToolDialogBase", "Add"))
        self.pushButton_2.setText(_translate("HcqiToolDialogBase", "Layout"))
        self.pushButton_5.setText(_translate("HcqiToolDialogBase", "Export to KML"))
        self.label_8.setText(_translate("HcqiToolDialogBase", "Ouput Layout"))
        self.pushButton_7.setText(_translate("HcqiToolDialogBase", "Browse"))
        self.checkBox_2.setText(_translate("HcqiToolDialogBase", "Add hospital facilities"))
        self.checkBox_3.setText(_translate("HcqiToolDialogBase", "Add primary health care facilities"))
        self.pushButton_6.setText(_translate("HcqiToolDialogBase", "Export PQI variation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("HcqiToolDialogBase", "Mapping"))

